# Generated by Django 4.1.3 on 2023-01-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recomend_product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
