# Generated by Django 4.1.3 on 2022-12-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profilename',
            field=models.CharField(error_messages={'unique': 'profilename은 필수항목입니다'}, max_length=50, unique=True, verbose_name='회원이름'),
        ),
    ]
