# Generated by Django 4.1.3 on 2022-12-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
