# Generated by Django 4.1.3 on 2022-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
